
CC := g++

all: Motion
	$(CC)  Motion.o  $(shell pkg-config opencv --libs) -o Motion

Motion:Motion.cpp
	$(CC) -c -std=c++0x $(shell pkg-config opencv --cflags) Motion.cpp -o Motion.o

.PHONY: clean clean_file

clean:
	-rm *.o
	-rm Motion

clean_file:
	-rm record/avi/*.avi



